musicbot:
  image: szastupov/musicbot
  restart: always
  links:
    - mongo
  environment:
    - BOT_NAME=MusicCatalogBot
    - API_TOKEN=Telegram API token
    - BOTAN_TOKEN=NzQyNDgyMTc5MDUyNzk4MDU0.XzGwag.Hwzylk1pszy4QIpUpahM5QVXwCA
    - MONGO_HOST=mongo
mongo:
  image: mongo
  restart: always
